version: '3'
services:
  webdav:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./notes:/usr/local/apache2/notes
      - ./web:/usr/local/apache2/htdocs
      - ./certs:/etc/ssl/certs
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped
